<?php
namespace IComeFromTheNet\Ledger\Query;

use DBALGateway\Query\AbstractQuery;
use DBALGateway\Query\QueryInterface;

/**
  *  Vouch Type Query Builder
  *
  *  Voucher Types may share common name and slug but will have a different
  *  enabled date pair. They are a temporal entity.
  *
  *  For example, if change the prefix for sales recepits, that create a new type with
  *  same name. 
  *
  *  Each entity has a unique id generated by the database and that
  *  is used to create relationships in our domain.
  *
  *  A voucher slug name will is used to establish relationships in the domain.
  *  The ledger will only load the valid entities as of the given date, and
  *  for each name there can be only one valid entity at a given date.
  *
  *  To find all sales recepts transactions on ledger we would query for
  *  slug name sales_recepts in the implicit foreign key column in ledger transactions.
  *
  *  Using a loose forign key constrain (implicit) to avoid working with a combined
  *  primary key (slug,validFrom). SQL Databases do not support temporal tables and therefore force
  *  temporal validity checks are forcedback into the application code. Were make it easier on ourselves
  *  and use implicit relationship.
  *
  *  We can always set an index in the ledgerTransaction table on the slug name column.
  *
  *  @author Lewis Dyer <getintouch@icomefromthenet.com>
  *  @since 1.0.0
  */
class VouchTypeQuery extends AbstractQuery implements QueryInterface
{
    
}
/* End of Class */
